#!/usr/bin/env python
import sys
import rospy
from robot_recorder_core.recorder import Recorder


if __name__ == '__main__':
    rospy.init_node('record_states_to_keyframes', anonymous=True)
    argv = rospy.myargv()

    if len(argv) == 1:
        # Using default values
        freq = 10
        output_name = "record.json"
        manual = False
    elif len(argv) == 4:
        freq, output_name = argv[1:3]
        manual = argv[3].lower() == 'true'
    else:
        print "Wrong usage. Set arguments: frequency output_name"
        sys.exit (1)

    record = Recorder(freq, output_name, manual)
    rospy.spin()
